//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATABASE_BOEKEN_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boeken
    {
        public int Id { get; set; }
        public string Tittel { get; set; }
        public Nullable<int> AantalPaginas { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<System.DateTime> Publicatie { get; set; }
        public Nullable<int> UitgeverId { get; set; }
    }
}
